/*
# Seed 50 T-Shirts Products

Inserts 50 realistic t-shirt products with multiple colors, sizes, discount,
COD availability, and ratings. Idempotent via ON CONFLICT (slug) DO NOTHING.
*/

DO $$
DECLARE c_tees uuid;
BEGIN
  SELECT id INTO c_tees FROM public.categories WHERE slug='t-shirts';

  INSERT INTO public.products
    (name, slug, description, price, mrp, stock, low_stock_threshold, category_id, brand, rating, rating_count, badges, is_featured, is_trending, is_best_seller, is_new, primary_image_url, colors, sizes, discount, cod_available)
  SELECT
    p.name, p.slug, p.descr, p.price, p.mrp, p.stock, 10, c_tees, p.brand, p.rating, p.rc, p.badges, p.feat, p.trend, p.best, p.newb, p.img, p.colors, p.sizes, p.disc, true
  FROM (VALUES
    ('Black Oversized T-Shirt','black-oversized-tshirt','Heavyweight 240 GSM cotton oversized fit tee with drop shoulders. Premium matte finish.',799,1499,40,'Harsh Co.',4.5,128,ARRAY['Bestseller','Oversized'],true,true,true,false,'https://images.pexels.com/photos/1655532/pexels-photo-1655532.jpeg?auto=compress&cs=tinysrgb&w=800',ARRAY['Black','White','Grey'],ARRAY['S','M','L','XL','XXL'],47,true),
    ('White Printed T-Shirt','white-printed-tshirt','Soft bio-washed cotton tee with a bold graphic print. Relaxed regular fit.',899,1799,30,'Harsh Co.',4.4,96,ARRAY['Printed'],false,true,false,true,'https://images.pexels.com/photos/996329/pexels-photo-996329.jpeg?auto=compress&cs=tinysrgb&w=800',ARRAY['White','Black','Olive'],ARRAY['S','M','L','XL'],50,true),
    ('Grey Premium Cotton Tee','grey-premium-cotton-tee','180 GSM combed cotton with a tailored regular fit. Minimal gold-t embroidered chest detail.',999,1999,20,'Harsh Luxe',4.7,54,ARRAY['Premium'],true,false,true,false,'https://images.pexels.com/photos/1183266/pexels-photo-1183266.jpeg?auto=compress&cs=tinysrgb&w=800',ARRAY['Grey','Black','Navy'],ARRAY['S','M','L','XL','XXL'],50,true),
    ('Navy Stripe Tee','navy-stripe-tee','Classic horizontal stripe tee in navy and white. Breathable summer cotton.',749,1399,35,'Harsh Co.',4.2,40,ARRAY['New'],false,false,false,true,'https://images.pexels.com/photos/5383375/pexels-photo-5383375.jpeg?auto=compress&cs=tinysrgb&w=800',ARRAY['Navy/White','Black/White'],ARRAY['S','M','L','XL'],46,true),
    ('Maroon Henley Tee','maroon-henley-tee','Three-button henley in rich maroon. Premium slub cotton, regular fit.',849,1699,22,'Harsh Luxe',4.3,33,ARRAY['New','Henley'],false,true,false,true,'https://images.pexels.com/photos/769733/pexels-photo-769733.jpeg?auto=compress&cs=tinysrgb&w=800',ARRAY['Maroon','Black','Olive'],ARRAY['S','M','L','XL'],50,true),
    ('Olive Oversized Tee','olive-oversized-tee','Oversized boxy fit in earthy olive. 220 GSM heavyweight cotton.',899,1799,18,'Harsh Co.',4.6,28,ARRAY['Oversized','Olive'],true,true,false,false,'https://images.pexels.com/photos/1666071/pexels-photo-1666071.jpeg?auto=compress&cs=tinysrgb&w=800',ARRAY['Olive','Black','Beige'],ARRAY['S','M','L','XL','XXL'],50,true),
    ('White Graphic Tee','white-graphic-tee','Crew neck white tee with a bold front graphic. Soft cotton, regular fit.',799,1499,28,'Harsh Co.',4.4,72,ARRAY['Graphic'],false,true,true,false,'https://images.pexels.com/photos/996329/pexels-photo-996329.jpeg?auto=compress&cs=tinysrgb&w=800',ARRAY['White','Black'],ARRAY['S','M','L','XL'],47,true),
    ('Black Crew Neck Tee','black-crew-neck-tee','Essential black crew neck tee. 180 GSM cotton, pre-shrunk for a lasting fit.',699,1299,38,'Harsh Co.',4.3,85,ARRAY['Essential'],false,false,true,false,'https://images.pexels.com/photos/1655532/pexels-photo-1655532.jpeg?auto=compress&cs=tinysrgb&w=800',ARRAY['Black','White','Grey','Navy'],ARRAY['S','M','L','XL','XXL'],46,true),
    ('Charcoal Oversized Tee','charcoal-oversized-tee','Oversized fit tee in dark charcoal. Heavyweight cotton with a matte finish.',899,1799,20,'Harsh Co.',4.5,41,ARRAY['Oversized'],true,true,false,true,'https://images.pexels.com/photos/1183266/pexels-photo-1183266.jpeg?auto=compress&cs=tinysrgb&w=800',ARRAY['Charcoal','Black','Grey'],ARRAY['S','M','L','XL','XXL'],50,true),
    ('Burgundy Heavyweight Tee','burgundy-heavyweight-tee','240 GSM heavyweight tee in rich burgundy. Boxy fit, premium cotton.',949,1899,16,'Harsh Luxe',4.6,35,ARRAY['Heavyweight','Premium'],true,false,true,false,'https://images.pexels.com/photos/769733/pexels-photo-769733.jpeg?auto=compress&cs=tinysrgb&w=800',ARRAY['Burgundy','Maroon','Black'],ARRAY['S','M','L','XL'],50,true),
    ('White Drop Shoulder Tee','white-drop-shoulder-tee','White drop shoulder tee with an oversized silhouette. Modern streetwear.',899,1799,24,'Harsh Co.',4.4,52,ARRAY['Oversized','New'],false,true,false,true,'https://images.pexels.com/photos/996329/pexels-photo-996329.jpeg?auto=compress&cs=tinysrgb&w=800',ARRAY['White','Black','Grey'],ARRAY['S','M','L','XL'],50,true),
    ('Navy Plain Tee','navy-plain-tee','Essential navy blue tee. 180 GSM cotton, regular fit.',699,1299,32,'Harsh Co.',4.3,48,ARRAY['Essential'],false,false,false,false,'https://images.pexels.com/photos/5383375/pexels-photo-5383375.jpeg?auto=compress&cs=tinysrgb&w=800',ARRAY['Navy','Black','Grey'],ARRAY['S','M','L','XL'],46,true),
    ('Beige Oversized Tee','beige-oversized-tee','Beige oversized tee in heavyweight cotton. Minimalist earthy tone.',949,1899,18,'Harsh Luxe',4.6,29,ARRAY['Oversized','Premium'],true,false,true,false,'https://images.pexels.com/photos/1666071/pexels-photo-1666071.jpeg?auto=compress&cs=tinysrgb&w=800',ARRAY['Beige','Olive','White'],ARRAY['S','M','L','XL'],50,true),
    ('Black Graphic Tee','black-graphic-tee','Black tee with a bold white graphic print. Street-ready statement piece.',849,1699,26,'Harsh Co.',4.5,61,ARRAY['Graphic'],false,true,false,false,'https://images.pexels.com/photos/1655532/pexels-photo-1655532.jpeg?auto=compress&cs=tinysrgb&w=800',ARRAY['Black','White'],ARRAY['S','M','L','XL'],50,true),
    ('Olive Henley Tee','olive-henley-tee','Olive henley tee with a three-button placket. Soft slub cotton regular fit.',899,1799,19,'Harsh Luxe',4.5,24,ARRAY['Henley','New'],false,false,false,true,'https://images.pexels.com/photos/769733/pexels-photo-769733.jpeg?auto=compress&cs=tinysrgb&w=800',ARRAY['Olive','Khaki','Black'],ARRAY['S','M','L','XL'],50,true),
    ('White Premium Cotton Tee','white-premium-cotton-tee','180 GSM premium combed cotton tee in white. Tailored regular fit.',949,1899,22,'Harsh Luxe',4.7,38,ARRAY['Premium'],true,false,true,false,'https://images.pexels.com/photos/996329/pexels-photo-996329.jpeg?auto=compress&cs=tinysrgb&w=800',ARRAY['White','Black','Navy'],ARRAY['S','M','L','XL','XXL'],50,true),
    ('Grey Oversized Tee','grey-oversized-tee','Grey oversized tee with drop shoulders. Heavyweight cotton boxy fit.',899,1799,20,'Harsh Co.',4.5,44,ARRAY['Oversized'],true,true,false,false,'https://images.pexels.com/photos/1183266/pexels-photo-1183266.jpeg?auto=compress&cs=tinysrgb&w=800',ARRAY['Grey','Charcoal','Black'],ARRAY['S','M','L','XL','XXL'],50,true),
    ('Black Stripe Tee','black-stripe-tee','Black and white horizontal stripe tee. A timeless nautical-inspired style.',849,1699,24,'Harsh Co.',4.4,36,ARRAY['Striped'],false,false,false,false,'https://images.pexels.com/photos/5383375/pexels-photo-5383375.jpeg?auto=compress&cs=tinysrgb&w=800',ARRAY['Black/White','Navy/White'],ARRAY['S','M','L','XL'],50,true),
    ('Mustard Crew Neck Tee','mustard-crew-neck-tee','Mustard yellow crew neck tee. A pop of color for casual styling.',799,1599,28,'Harsh Co.',4.3,31,ARRAY['Casual','New'],false,true,false,true,'https://images.pexels.com/photos/1655532/pexels-photo-1655532.jpeg?auto=compress&cs=tinysrgb&w=800',ARRAY['Mustard','Olive','Black'],ARRAY['S','M','L','XL'],50,true),
    ('Premium Black Tee','premium-black-tee','240 GSM heavyweight black tee in a tailored regular fit. Premium matte finish.',1099,2199,14,'Harsh Luxe',4.8,42,ARRAY['Premium','Heavyweight'],true,true,true,false,'https://images.pexels.com/photos/1655532/pexels-photo-1655532.jpeg?auto=compress&cs=tinysrgb&w=800',ARRAY['Black','Charcoal','White'],ARRAY['S','M','L','XL','XXL'],50,true),
    ('Rust Oversized Tee','rust-oversized-tee','Oversized tee in warm rust. Earthy tone, heavyweight cotton.',949,1899,17,'Harsh Co.',4.6,27,ARRAY['Oversized','New'],true,true,false,true,'https://images.pexels.com/photos/1666071/pexels-photo-1666071.jpeg?auto=compress&cs=tinysrgb&w=800',ARRAY['Rust','Olive','Beige'],ARRAY['S','M','L','XL'],50,true),
    ('White Oversized Tee','white-oversized-tee','White oversized tee with drop shoulders. Heavyweight cotton, boxy fit.',899,1799,22,'Harsh Co.',4.5,50,ARRAY['Oversized','Bestseller'],true,true,true,false,'https://images.pexels.com/photos/996329/pexels-photo-996329.jpeg?auto=compress&cs=tinysrgb&w=800',ARRAY['White','Black','Grey'],ARRAY['S','M','L','XL','XXL'],50,true),
    ('Forest Green Tee','forest-green-tee','Forest green essential tee. 180 GSM cotton, regular fit.',749,1499,30,'Harsh Co.',4.3,33,ARRAY['Essential'],false,false,false,false,'https://images.pexels.com/photos/5383375/pexels-photo-5383375.jpeg?auto=compress&cs=tinysrgb&w=800',ARRAY['Forest Green','Olive','Black'],ARRAY['S','M','L','XL'],50,true),
    ('Wine Heavyweight Tee','wine-heavyweight-tee','240 GSM heavyweight tee in wine. Rich color, boxy oversized fit.',949,1899,16,'Harsh Luxe',4.6,25,ARRAY['Heavyweight','Premium'],true,false,true,false,'https://images.pexels.com/photos/769733/pexels-photo-769733.jpeg?auto=compress&cs=tinysrgb&w=800',ARRAY['Wine','Maroon','Black'],ARRAY['S','M','L','XL'],50,true),
    ('Light Blue Graphic Tee','light-blue-graphic-tee','Light blue tee with a front graphic print. A fresh, casual style.',849,1699,20,'Harsh Co.',4.4,29,ARRAY['Graphic','New'],false,true,false,true,'https://images.pexels.com/photos/996329/pexels-photo-996329.jpeg?auto=compress&cs=tinysrgb&w=800',ARRAY['Light Blue','White'],ARRAY['S','M','L','XL'],50,true),
    ('Black Pocket Tee','black-pocket-tee','Black tee with a chest pocket. Minimalist essential, regular fit.',749,1499,26,'Harsh Co.',4.4,37,ARRAY['Essential'],false,false,false,false,'https://images.pexels.com/photos/1655532/pexels-photo-1655532.jpeg?auto=compress&cs=tinysrgb&w=800',ARRAY['Black','Grey','Navy'],ARRAY['S','M','L','XL'],50,true),
    ('Sage Green Oversized Tee','sage-green-oversized-tee','Oversized tee in muted sage green. Soft heavyweight cotton, boxy fit.',999,1999,15,'Harsh Luxe',4.7,23,ARRAY['Oversized','Premium'],true,true,false,true,'https://images.pexels.com/photos/1666071/pexels-photo-1666071.jpeg?auto=compress&cs=tinysrgb&w=800',ARRAY['Sage Green','Olive','Grey'],ARRAY['S','M','L','XL'],50,true),
    ('White Striped Tee','white-striped-tee','White tee with navy stripes. A fresh, classic nautical style.',799,1599,24,'Harsh Co.',4.4,35,ARRAY['Striped'],false,false,false,false,'https://images.pexels.com/photos/5383375/pexels-photo-5383375.jpeg?auto=compress&cs=tinysrgb&w=800',ARRAY['White/Navy','White/Black'],ARRAY['S','M','L','XL'],50,true),
    ('Brown Oversized Tee','brown-oversized-tee','Oversized tee in chocolate brown. Earthy tone, heavyweight cotton.',949,1899,18,'Harsh Co.',4.5,22,ARRAY['Oversized','New'],false,true,false,true,'https://images.pexels.com/photos/1666071/pexels-photo-1666071.jpeg?auto=compress&cs=tinysrgb&w=800',ARRAY['Brown','Rust','Olive'],ARRAY['S','M','L','XL'],50,true),
    ('Maroon Oversized Tee','maroon-oversized-tee','Maroon oversized tee with drop shoulders. Heavyweight cotton, boxy fit.',899,1799,20,'Harsh Co.',4.5,30,ARRAY['Oversized'],true,true,false,false,'https://images.pexels.com/photos/769733/pexels-photo-769733.jpeg?auto=compress&cs=tinysrgb&w=800',ARRAY['Maroon','Wine','Black'],ARRAY['S','M','L','XL','XXL'],50,true),
    ('Sky Blue Crew Neck Tee','sky-blue-crew-neck-tee','Sky blue essential tee. Soft cotton, regular fit for daily wear.',749,1499,28,'Harsh Co.',4.3,41,ARRAY['Essential'],false,false,false,false,'https://images.pexels.com/photos/996329/pexels-photo-996329.jpeg?auto=compress&cs=tinysrgb&w=800',ARRAY['Sky Blue','White'],ARRAY['S','M','L','XL'],50,true),
    ('Premium Grey Tee','premium-grey-tee','240 GSM heavyweight grey tee. Tailored regular fit, premium combed cotton.',1099,2199,12,'Harsh Luxe',4.8,36,ARRAY['Premium','Heavyweight'],true,true,true,false,'https://images.pexels.com/photos/1183266/pexels-photo-1183266.jpeg?auto=compress&cs=tinysrgb&w=800',ARRAY['Grey','Charcoal','Black'],ARRAY['S','M','L','XL','XXL'],50,true),
    ('Black V-Neck Tee','black-v-neck-tee','Black v-neck tee. A sleek alternative to the classic crew neck.',749,1499,26,'Harsh Co.',4.4,39,ARRAY['V-Neck'],false,false,false,false,'https://images.pexels.com/photos/1655532/pexels-photo-1655532.jpeg?auto=compress&cs=tinysrgb&w=800',ARRAY['Black','White','Grey'],ARRAY['S','M','L','XL'],50,true),
    ('Khaki Oversized Tee','khaki-oversized-tee','Khaki oversized tee with drop shoulders. Earthy and versatile.',899,1799,19,'Harsh Co.',4.5,24,ARRAY['Oversized'],false,true,false,true,'https://images.pexels.com/photos/1666071/pexels-photo-1666071.jpeg?auto=compress&cs=tinysrgb&w=800',ARRAY['Khaki','Olive','Beige'],ARRAY['S','M','L','XL'],50,true),
    ('Cream Heavyweight Tee','cream-heavyweight-tee','240 GSM heavyweight tee in cream. Premium cotton, boxy fit.',999,1999,16,'Harsh Luxe',4.7,21,ARRAY['Heavyweight','Premium'],true,false,true,false,'https://images.pexels.com/photos/1666071/pexels-photo-1666071.jpeg?auto=compress&cs=tinysrgb&w=800',ARRAY['Cream','Off-White','Beige'],ARRAY['S','M','L','XL'],50,true),
    ('Navy Oversized Tee','navy-oversized-tee','Navy oversized tee with drop shoulders. Heavyweight cotton, boxy fit.',899,1799,21,'Harsh Co.',4.5,33,ARRAY['Oversized'],true,true,false,false,'https://images.pexels.com/photos/5383375/pexels-photo-5383375.jpeg?auto=compress&cs=tinysrgb&w=800',ARRAY['Navy','Black','Grey'],ARRAY['S','M','L','XL','XXL'],50,true),
    ('Olive Graphic Tee','olive-graphic-tee','Olive tee with a bold front graphic. A standout streetwear piece.',849,1699,22,'Harsh Co.',4.5,28,ARRAY['Graphic','New'],false,true,false,true,'https://images.pexels.com/photos/1655532/pexels-photo-1655532.jpeg?auto=compress&cs=tinysrgb&w=800',ARRAY['Olive','Black','Khaki'],ARRAY['S','M','L','XL'],50,true),
    ('White Henley Tee','white-henley-tee','White henley tee with a three-button placket. Soft cotton, regular fit.',899,1799,18,'Harsh Luxe',4.5,19,ARRAY['Henley'],false,false,false,false,'https://images.pexels.com/photos/996329/pexels-photo-996329.jpeg?auto=compress&cs=tinysrgb&w=800',ARRAY['White','Black','Grey'],ARRAY['S','M','L','XL'],50,true),
    ('Peach Crew Neck Tee','peach-crew-neck-tee','Peach crew neck tee in soft cotton. A warm, fresh summer color.',799,1599,24,'Harsh Co.',4.4,26,ARRAY['Casual','New'],false,true,false,true,'https://images.pexels.com/photos/769733/pexels-photo-769733.jpeg?auto=compress&cs=tinysrgb&w=800',ARRAY['Peach','Cream','White'],ARRAY['S','M','L','XL'],50,true),
    ('Charcoal Graphic Tee','charcoal-graphic-tee','Charcoal tee with a minimal front graphic. Understated streetwear.',849,1699,20,'Harsh Co.',4.5,31,ARRAY['Graphic'],false,false,false,false,'https://images.pexels.com/photos/1183266/pexels-photo-1183266.jpeg?auto=compress&cs=tinysrgb&w=800',ARRAY['Charcoal','Black','Grey'],ARRAY['S','M','L','XL'],50,true),
    ('Olive Premium Tee','olive-premium-tee','240 GSM premium tee in olive. Tailored regular fit, heavyweight cotton.',1099,2199,13,'Harsh Luxe',4.8,22,ARRAY['Premium','Heavyweight'],true,false,true,false,'https://images.pexels.com/photos/1666071/pexels-photo-1666071.jpeg?auto=compress&cs=tinysrgb&w=800',ARRAY['Olive','Khaki','Black'],ARRAY['S','M','L','XL','XXL'],50,true),
    ('Black Heavyweight Tee','black-heavyweight-tee','240 GSM heavyweight black tee. Boxy oversized fit, premium cotton.',999,1999,17,'Harsh Luxe',4.7,45,ARRAY['Heavyweight','Bestseller'],true,true,true,false,'https://images.pexels.com/photos/1655532/pexels-photo-1655532.jpeg?auto=compress&cs=tinysrgb&w=800',ARRAY['Black','Charcoal','White'],ARRAY['S','M','L','XL','XXL'],50,true),
    ('White Crew Neck Tee','white-crew-neck-tee','Essential white crew neck tee. 180 GSM cotton, pre-shrunk regular fit.',699,1299,34,'Harsh Co.',4.3,58,ARRAY['Essential'],false,false,true,false,'https://images.pexels.com/photos/996329/pexels-photo-996329.jpeg?auto=compress&cs=tinysrgb&w=800',ARRAY['White','Black','Grey','Navy'],ARRAY['S','M','L','XL','XXL'],46,true),
    ('Grey Stripe Tee','grey-stripe-tee','Grey and white horizontal stripe tee. A versatile, classic style.',799,1599,22,'Harsh Co.',4.4,27,ARRAY['Striped'],false,false,false,false,'https://images.pexels.com/photos/5383375/pexels-photo-5383375.jpeg?auto=compress&cs=tinysrgb&w=800',ARRAY['Grey/White','Black/White'],ARRAY['S','M','L','XL'],50,true),
    ('Wine Oversized Tee','wine-oversized-tee','Wine oversized tee with drop shoulders. Rich color, heavyweight cotton.',899,1799,19,'Harsh Co.',4.5,25,ARRAY['Oversized','New'],true,true,false,true,'https://images.pexels.com/photos/769733/pexels-photo-769733.jpeg?auto=compress&cs=tinysrgb&w=800',ARRAY['Wine','Maroon','Black'],ARRAY['S','M','L','XL','XXL'],50,true),
    ('Teal Crew Neck Tee','teal-crew-neck-tee','Teal crew neck tee. A distinctive color for casual everyday styling.',799,1599,21,'Harsh Co.',4.4,23,ARRAY['Casual'],false,false,false,false,'https://images.pexels.com/photos/5383375/pexels-photo-5383375.jpeg?auto=compress&cs=tinysrgb&w=800',ARRAY['Teal','Navy','Black'],ARRAY['S','M','L','XL'],50,true),
    ('Premium White Tee','premium-white-tee','240 GSM premium white tee. Tailored regular fit, heavyweight cotton.',1099,2199,14,'Harsh Luxe',4.8,34,ARRAY['Premium','Heavyweight'],true,true,true,false,'https://images.pexels.com/photos/996329/pexels-photo-996329.jpeg?auto=compress&cs=tinysrgb&w=800',ARRAY['White','Black','Grey'],ARRAY['S','M','L','XL','XXL'],50,true),
    ('Black Drop Shoulder Tee','black-drop-shoulder-tee','Black drop shoulder tee with an oversized silhouette. Modern streetwear.',899,1799,23,'Harsh Co.',4.5,40,ARRAY['Oversized'],false,true,false,false,'https://images.pexels.com/photos/1655532/pexels-photo-1655532.jpeg?auto=compress&cs=tinysrgb&w=800',ARRAY['Black','Charcoal','White'],ARRAY['S','M','L','XL','XXL'],50,true),
    ('Rust Crew Neck Tee','rust-crew-neck-tee','Rust crew neck tee in soft cotton. A warm, earthy color for casual styling.',799,1599,25,'Harsh Co.',4.4,24,ARRAY['Casual','New'],false,false,false,true,'https://images.pexels.com/photos/1666071/pexels-photo-1666071.jpeg?auto=compress&cs=tinysrgb&w=800',ARRAY['Rust','Olive','Brown'],ARRAY['S','M','L','XL'],50,true),
    ('Maroon Crew Neck Tee','maroon-crew-neck-tee','Maroon essential tee. 180 GSM cotton, regular fit for daily wear.',749,1499,29,'Harsh Co.',4.3,36,ARRAY['Essential'],false,false,false,false,'https://images.pexels.com/photos/769733/pexels-photo-769733.jpeg?auto=compress&cs=tinysrgb&w=800',ARRAY['Maroon','Wine','Black'],ARRAY['S','M','L','XL'],50,true)
  ) AS p(name, slug, descr, price, mrp, stock, brand, rating, rc, badges, feat, trend, best, newb, img, colors, sizes, disc, cod)
  ON CONFLICT (slug) DO NOTHING;
END $$;
