/*
# Seed 50 Shirts Products

Inserts 50 realistic shirt products with multiple colors, sizes, discount,
COD availability, and ratings. Idempotent via ON CONFLICT (slug) DO NOTHING.
*/

DO $$
DECLARE c_shirts uuid;
BEGIN
  SELECT id INTO c_shirts FROM public.categories WHERE slug='shirts';

  INSERT INTO public.products
    (name, slug, description, price, mrp, stock, low_stock_threshold, category_id, brand, rating, rating_count, badges, is_featured, is_trending, is_best_seller, is_new, primary_image_url, colors, sizes, discount, cod_available)
  SELECT
    p.name, p.slug, p.descr, p.price, p.mrp, p.stock, 10, c_shirts, p.brand, p.rating, p.rc, p.badges, p.feat, p.trend, p.best, p.newb, p.img, p.colors, p.sizes, p.disc, true
  FROM (VALUES
    ('Black Formal Shirt','black-formal-shirt','Wrinkle-resistant formal shirt with a spread collar. Slim fit, rich black twill.',1499,2999,18,'Harsh Formals',4.6,72,ARRAY['Formal'],true,false,true,false,'https://images.pexels.com/photos/2974409/pexels-photo-2974409.jpeg?auto=compress&cs=tinysrgb&w=800',ARRAY['Black','White','Navy'],ARRAY['S','M','L','XL','XXL'],50,true),
    ('White Casual Shirt','white-casual-shirt','Linen-blend casual shirt with a relaxed fit. Perfect for everyday styling.',1299,2499,25,'Harsh Co.',4.4,61,ARRAY['Casual'],false,true,false,true,'https://images.pexels.com/photos/2974396/pexels-photo-2974396.jpeg?auto=compress&cs=tinysrgb&w=800',ARRAY['White','Sky','Pink'],ARRAY['S','M','L','XL'],48,true),
    ('Denim Shirt','denim-shirt','Mid-wash denim shirt with a button-down collar. Versatile layering piece.',1799,3499,14,'Harsh Denim',4.7,45,ARRAY['Denim','Bestseller'],true,true,true,false,'https://images.pexels.com/photos/4308801/pexels-photo-4308801.jpeg?auto=compress&cs=tinysrgb&w=800',ARRAY['Blue','Light Blue','Black'],ARRAY['S','M','L','XL'],49,true),
    ('Light Blue Oxford Shirt','light-blue-oxford-shirt','Pinpoint oxford weave with a button-down collar. A timeless wardrobe staple.',1399,2699,30,'Harsh Formals',4.5,38,ARRAY['Oxford'],false,false,false,false,'https://images.pexels.com/photos/8214843/pexels-photo-8214843.jpeg?auto=compress&cs=tinysrgb&w=800',ARRAY['Light Blue','White','Pink'],ARRAY['S','M','L','XL','XXL'],48,true),
    ('Checked Flannel Shirt','checked-flannel-shirt','Brushed flannel in red and black checks. Soft, warm, and effortlessly stylish.',1599,3099,16,'Harsh Co.',4.3,29,ARRAY['Flannel','New'],false,true,false,true,'https://images.pexels.com/photos/1043474/pexels-photo-1043474.jpeg?auto=compress&cs=tinysrgb&w=800',ARRAY['Red/Black','Green/Black','Blue/Black'],ARRAY['S','M','L','XL'],48,true),
    ('Peach Linen Shirt','peach-linen-shirt','Lightweight pure linen shirt in a soft peach tone. Holiday-ready breathable weave.',1699,3299,12,'Harsh Luxe',4.8,21,ARRAY['Linen','Premium'],true,false,true,true,'https://images.pexels.com/photos/769749/pexels-photo-769749.jpeg?auto=compress&cs=tinysrgb&w=800',ARRAY['Peach','White','Sky'],ARRAY['S','M','L','XL'],49,true),
    ('White Slim Fit Shirt','white-slim-fit-shirt','Crisp white slim fit shirt with a cutaway collar. Boardroom to dinner ready.',1499,2899,20,'Harsh Formals',4.5,55,ARRAY['Slim','Formal'],true,false,true,false,'https://images.pexels.com/photos/2974409/pexels-photo-2974409.jpeg?auto=compress&cs=tinysrgb&w=800',ARRAY['White','Sky','Light Pink'],ARRAY['S','M','L','XL'],48,true),
    ('Black Overshirt','black-overshirt','Heavyweight black overshirt that doubles as a light jacket. Streetwear staple.',1899,3699,13,'Harsh Co.',4.6,34,ARRAY['Overshirt','Trending'],true,true,false,true,'https://images.pexels.com/photos/1183266/pexels-photo-1183266.jpeg?auto=compress&cs=tinysrgb&w=800',ARRAY['Black','Olive','Navy'],ARRAY['M','L','XL','XXL'],49,true),
    ('Sky Blue Striped Shirt','sky-blue-striped-shirt','Sky blue and white striped shirt. A fresh take on the classic office shirt.',1399,2699,22,'Harsh Formals',4.4,41,ARRAY['Striped'],false,false,false,false,'https://images.pexels.com/photos/8214843/pexels-photo-8214843.jpeg?auto=compress&cs=tinysrgb&w=800',ARRAY['Sky Blue','White'],ARRAY['S','M','L','XL'],48,true),
    ('Burgundy Casual Shirt','burgundy-casual-shirt','Rich burgundy casual shirt in brushed cotton. Soft hand-feel, relaxed fit.',1499,2899,18,'Harsh Co.',4.5,33,ARRAY['Casual'],false,true,false,false,'https://images.pexels.com/photos/1043474/pexels-photo-1043474.jpeg?auto=compress&cs=tinysrgb&w=800',ARRAY['Burgundy','Maroon'],ARRAY['S','M','L','XL'],48,true),
    ('Navy Linen Shirt','navy-linen-shirt','Pure linen shirt in deep navy. Breathable, lightweight, and elegant.',1699,3299,14,'Harsh Luxe',4.7,26,ARRAY['Linen','Premium'],true,false,true,false,'https://images.pexels.com/photos/769749/pexels-photo-769749.jpeg?auto=compress&cs=tinysrgb&w=800',ARRAY['Navy','White','Sky'],ARRAY['S','M','L','XL'],49,true),
    ('Classic White Shirt','classic-white-shirt','A timeless white shirt in premium cotton poplin. The ultimate wardrobe essential.',1299,2499,28,'Harsh Formals',4.5,62,ARRAY['Classic','Essential'],false,false,true,false,'https://images.pexels.com/photos/2974396/pexels-photo-2974396.jpeg?auto=compress&cs=tinysrgb&w=800',ARRAY['White'],ARRAY['S','M','L','XL','XXL'],48,true),
    ('Pink Oxford Shirt','pink-oxford-shirt','Pink oxford cloth shirt with a button-down collar. A modern classic.',1399,2699,19,'Harsh Formals',4.4,24,ARRAY['Oxford'],false,false,false,true,'https://images.pexels.com/photos/8214843/pexels-photo-8214843.jpeg?auto=compress&cs=tinysrgb&w=800',ARRAY['Pink','White','Sky'],ARRAY['S','M','L','XL'],48,true),
    ('Black Denim Shirt','black-denim-shirt','Black denim shirt with a rugged finish. A versatile layering essential.',1799,3499,15,'Harsh Denim',4.6,31,ARRAY['Denim'],true,true,false,false,'https://images.pexels.com/photos/4308801/pexels-photo-4308801.jpeg?auto=compress&cs=tinysrgb&w=800',ARRAY['Black','Grey'],ARRAY['S','M','L','XL'],49,true),
    ('Green Check Shirt','green-check-shirt','Green and black checked flannel shirt. Cozy and stylish for cooler days.',1599,3099,17,'Harsh Co.',4.3,22,ARRAY['Flannel','Check'],false,true,false,true,'https://images.pexels.com/photos/1043474/pexels-photo-1043474.jpeg?auto=compress&cs=tinysrgb&w=800',ARRAY['Green/Black'],ARRAY['S','M','L','XL'],48,true),
    ('Slim Fit Black Shirt','slim-fit-black-shirt','Minimalist slim fit black shirt. Sharp, versatile, and always in style.',1599,3099,16,'Harsh Formals',4.6,43,ARRAY['Slim','Formal'],true,false,true,false,'https://images.pexels.com/photos/2974409/pexels-photo-2974409.jpeg?auto=compress&cs=tinysrgb&w=800',ARRAY['Black','Charcoal'],ARRAY['S','M','L','XL'],48,true),
    ('Cream Mandarin Shirt','cream-mandarin-shirt','Cream shirt with a mandarin collar. Minimalist, elegant, and modern.',1699,3299,11,'Harsh Luxe',4.7,18,ARRAY['Mandarin','Premium'],true,false,true,true,'https://images.pexels.com/photos/769749/pexels-photo-769749.jpeg?auto=compress&cs=tinysrgb&w=800',ARRAY['Cream','Off-White'],ARRAY['S','M','L','XL'],49,true),
    ('Blue Check Flannel','blue-check-flannel','Blue and black check flannel shirt. Brushed cotton for all-day comfort.',1499,2899,20,'Harsh Co.',4.4,29,ARRAY['Flannel','Check'],false,false,false,false,'https://images.pexels.com/photos/1043474/pexels-photo-1043474.jpeg?auto=compress&cs=tinysrgb&w=800',ARRAY['Blue/Black','Blue/Green'],ARRAY['S','M','L','XL'],48,true),
    ('Olive Casual Shirt','olive-casual-shirt','Olive green casual shirt in garment-dyed twill. Earthy and versatile.',1499,2899,18,'Harsh Co.',4.5,27,ARRAY['Casual'],false,true,false,true,'https://images.pexels.com/photos/1183266/pexels-photo-1183266.jpeg?auto=compress&cs=tinysrgb&w=800',ARRAY['Olive','Khaki','Black'],ARRAY['S','M','L','XL'],48,true),
    ('White Band Collar Shirt','white-band-collar-shirt','White shirt with a band collar for a clean, collarless look. Modern minimalism.',1599,3099,14,'Harsh Formals',4.6,20,ARRAY['Band Collar'],false,false,false,false,'https://images.pexels.com/photos/2974396/pexels-photo-2974396.jpeg?auto=compress&cs=tinysrgb&w=800',ARRAY['White','Sky'],ARRAY['S','M','L','XL'],48,true),
    ('Charcoal Formal Shirt','charcoal-formal-shirt','Charcoal grey formal shirt in a slim fit. Professional and polished.',1499,2899,17,'Harsh Formals',4.5,36,ARRAY['Formal'],false,false,true,false,'https://images.pexels.com/photos/2974409/pexels-photo-2974409.jpeg?auto=compress&cs=tinysrgb&w=800',ARRAY['Charcoal','Grey','Black'],ARRAY['S','M','L','XL'],48,true),
    ('Mid-Wash Denim Shirt','mid-wash-denim-shirt','Classic mid-wash denim shirt. A timeless layering piece for all seasons.',1699,3299,16,'Harsh Denim',4.5,28,ARRAY['Denim'],false,false,false,false,'https://images.pexels.com/photos/4308801/pexels-photo-4308801.jpeg?auto=compress&cs=tinysrgb&w=800',ARRAY['Blue','Light Blue'],ARRAY['S','M','L','XL'],48,true),
    ('White Cuban Shirt','white-cuban-shirt','White Cuban collar shirt with a retro camp-collar silhouette. Resort-ready.',1799,3499,12,'Harsh Luxe',4.7,23,ARRAY['Cuban','Premium'],true,true,false,true,'https://images.pexels.com/photos/769749/pexels-photo-769749.jpeg?auto=compress&cs=tinysrgb&w=800',ARRAY['White','Sky','Peach'],ARRAY['S','M','L','XL'],49,true),
    ('Maroon Formal Shirt','maroon-formal-shirt','Maroon formal shirt with a semi-spread collar. A distinguished formal choice.',1599,3099,15,'Harsh Formals',4.5,19,ARRAY['Formal'],false,false,false,false,'https://images.pexels.com/photos/2974409/pexels-photo-2974409.jpeg?auto=compress&cs=tinysrgb&w=800',ARRAY['Maroon','Burgundy'],ARRAY['S','M','L','XL'],48,true),
    ('Striped Linen Shirt','striped-linen-shirt','Linen shirt with vertical stripes. Lightweight and breezy for warm days.',1799,3499,13,'Harsh Luxe',4.6,17,ARRAY['Linen','Striped'],true,false,false,true,'https://images.pexels.com/photos/769749/pexels-photo-769749.jpeg?auto=compress&cs=tinysrgb&w=800',ARRAY['Sky/White','Navy/White'],ARRAY['S','M','L','XL'],49,true),
    ('Black Check Shirt','black-check-shirt','Black and grey micro-check shirt. Subtle pattern for smart-casual styling.',1499,2899,19,'Harsh Co.',4.4,25,ARRAY['Check'],false,false,false,false,'https://images.pexels.com/photos/1043474/pexels-photo-1043474.jpeg?auto=compress&cs=tinysrgb&w=800',ARRAY['Black/Grey'],ARRAY['S','M','L','XL'],48,true),
    ('Royal Blue Shirt','royal-blue-shirt','Royal blue cotton shirt with a regular fit. A bold pop of color.',1499,2899,21,'Harsh Formals',4.5,31,ARRAY['Casual','New'],false,true,false,true,'https://images.pexels.com/photos/8214843/pexels-photo-8214843.jpeg?auto=compress&cs=tinysrgb&w=800',ARRAY['Royal Blue','Navy'],ARRAY['S','M','L','XL'],48,true),
    ('Off-White Casual Shirt','off-white-casual-shirt','Off-white casual shirt in linen-cotton blend. Relaxed fit for easy styling.',1599,3099,16,'Harsh Co.',4.5,22,ARRAY['Casual'],false,false,false,false,'https://images.pexels.com/photos/2974396/pexels-photo-2974396.jpeg?auto=compress&cs=tinysrgb&w=800',ARRAY['Off-White','Cream'],ARRAY['S','M','L','XL'],48,true),
    ('Navy Pinstripe Shirt','navy-pinstripe-shirt','Navy pinstripe shirt for a sharp, professional look. Slim fit.',1699,3299,14,'Harsh Formals',4.6,18,ARRAY['Pinstripe','Formal'],true,false,true,false,'https://images.pexels.com/photos/2974409/pexels-photo-2974409.jpeg?auto=compress&cs=tinysrgb&w=800',ARRAY['Navy','Blue'],ARRAY['S','M','L','XL'],48,true),
    ('Rust Linen Shirt','rust-linen-shirt','Rust-colored pure linen shirt. Warm tones for an autumn-ready look.',1799,3499,11,'Harsh Luxe',4.7,16,ARRAY['Linen','Premium'],true,true,false,true,'https://images.pexels.com/photos/769749/pexels-photo-769749.jpeg?auto=compress&cs=tinysrgb&w=800',ARRAY['Rust','Orange'],ARRAY['S','M','L','XL'],49,true),
    ('Grey Casual Shirt','grey-casual-shirt','Heather grey casual shirt in soft cotton flannel. Effortlessly comfortable.',1399,2699,23,'Harsh Co.',4.3,34,ARRAY['Casual'],false,false,false,false,'https://images.pexels.com/photos/1183266/pexels-photo-1183266.jpeg?auto=compress&cs=tinysrgb&w=800',ARRAY['Grey','Charcoal'],ARRAY['S','M','L','XL'],48,true),
    ('Blue Cuban Collar Shirt','blue-cuban-collar-shirt','Blue Cuban collar shirt with a relaxed camp fit. Vintage summer style.',1799,3499,13,'Harsh Luxe',4.6,20,ARRAY['Cuban','New'],false,true,false,true,'https://images.pexels.com/photos/769749/pexels-photo-769749.jpeg?auto=compress&cs=tinysrgb&w=800',ARRAY['Blue','Navy'],ARRAY['S','M','L','XL'],48,true),
    ('White Overshirt','white-overshirt','White heavyweight overshirt. Layer it as a light jacket or wear it buttoned up.',1899,3699,10,'Harsh Co.',4.7,15,ARRAY['Overshirt','Premium'],true,false,true,false,'https://images.pexels.com/photos/1183266/pexels-photo-1183266.jpeg?auto=compress&cs=tinysrgb&w=800',ARRAY['White','Off-White'],ARRAY['M','L','XL'],49,true),
    ('Slim Fit Blue Shirt','slim-fit-blue-shirt','Slim fit blue shirt with a semi-spread collar. Crisp and professional.',1499,2899,18,'Harsh Formals',4.5,29,ARRAY['Slim','Formal'],false,false,false,false,'https://images.pexels.com/photos/8214843/pexels-photo-8214843.jpeg?auto=compress&cs=tinysrgb&w=800',ARRAY['Blue','Sky','Navy'],ARRAY['S','M','L','XL'],48,true),
    ('Beige Linen Shirt','beige-linen-shirt','Beige pure linen shirt with a relaxed fit. Minimalist summer elegance.',1699,3299,14,'Harsh Luxe',4.6,18,ARRAY['Linen','Premium'],true,false,false,true,'https://images.pexels.com/photos/769749/pexels-photo-769749.jpeg?auto=compress&cs=tinysrgb&w=800',ARRAY['Beige','Cream'],ARRAY['S','M','L','XL'],49,true),
    ('Red Check Flannel','red-check-flannel','Red and black check flannel shirt. A cozy, classic layering piece.',1599,3099,17,'Harsh Co.',4.4,26,ARRAY['Flannel','Check'],false,true,false,false,'https://images.pexels.com/photos/1043474/pexels-photo-1043474.jpeg?auto=compress&cs=tinysrgb&w=800',ARRAY['Red/Black'],ARRAY['S','M','L','XL'],48,true),
    ('Navy Formal Shirt','navy-formal-shirt','Navy formal shirt in premium twill. A versatile formal essential.',1599,3099,16,'Harsh Formals',4.5,24,ARRAY['Formal'],false,false,true,false,'https://images.pexels.com/photos/2974409/pexels-photo-2974409.jpeg?auto=compress&cs=tinysrgb&w=800',ARRAY['Navy','Blue','Black'],ARRAY['S','M','L','XL'],48,true),
    ('Light Pink Shirt','light-pink-shirt','Light pink cotton shirt. A refined and modern color for the discerning.',1499,2899,15,'Harsh Formals',4.5,17,ARRAY['Casual','New'],false,false,false,true,'https://images.pexels.com/photos/8214843/pexels-photo-8214843.jpeg?auto=compress&cs=tinysrgb&w=800',ARRAY['Light Pink','White'],ARRAY['S','M','L','XL'],48,true),
    ('Black Cuban Shirt','black-cuban-shirt','Black Cuban collar shirt in premium cotton. Sleek resortwear with a dark twist.',1899,3699,12,'Harsh Luxe',4.7,21,ARRAY['Cuban','Premium'],true,true,false,false,'https://images.pexels.com/photos/769749/pexels-photo-769749.jpeg?auto=compress&cs=tinysrgb&w=800',ARRAY['Black','Navy'],ARRAY['S','M','L','XL'],49,true),
    ('Washed Denim Shirt','washed-denim-shirt','Light-washed denim shirt with a relaxed fit. A breezy take on denim.',1699,3299,15,'Harsh Denim',4.5,22,ARRAY['Denim'],false,false,false,false,'https://images.pexels.com/photos/4308801/pexels-photo-4308801.jpeg?auto=compress&cs=tinysrgb&w=800',ARRAY['Light Blue','Washed Blue'],ARRAY['S','M','L','XL'],48,true),
    ('Green Casual Shirt','green-casual-shirt','Olive green casual shirt in twill weave. A versatile earthy tone.',1499,2899,19,'Harsh Co.',4.4,23,ARRAY['Casual'],false,false,false,false,'https://images.pexels.com/photos/1183266/pexels-photo-1183266.jpeg?auto=compress&cs=tinysrgb&w=800',ARRAY['Olive','Forest'],ARRAY['S','M','L','XL'],48,true),
    ('White Stripe Shirt','white-stripe-shirt','White shirt with subtle blue stripes. A refined, easy-to-style piece.',1599,3099,16,'Harsh Formals',4.5,19,ARRAY['Striped'],false,false,false,false,'https://images.pexels.com/photos/2974396/pexels-photo-2974396.jpeg?auto=compress&cs=tinysrgb&w=800',ARRAY['White/Blue','White/Grey'],ARRAY['S','M','L','XL'],48,true),
    ('Mustard Linen Shirt','mustard-linen-shirt','Mustard pure linen shirt. A bold, warm color for a standout summer look.',1799,3499,11,'Harsh Luxe',4.7,14,ARRAY['Linen','Premium'],true,true,false,true,'https://images.pexels.com/photos/769749/pexels-photo-769749.jpeg?auto=compress&cs=tinysrgb&w=800',ARRAY['Mustard','Yellow'],ARRAY['S','M','L','XL'],49,true),
    ('Grey Check Casual Shirt','grey-check-casual-shirt','Grey and black check shirt in soft flannel. Comfortable and stylish.',1499,2899,18,'Harsh Co.',4.4,21,ARRAY['Check','Casual'],false,false,false,false,'https://images.pexels.com/photos/1043474/pexels-photo-1043474.jpeg?auto=compress&cs=tinysrgb&w=800',ARRAY['Grey/Black'],ARRAY['S','M','L','XL'],48,true),
    ('White Grandad Shirt','white-grandad-shirt','White grandad shirt with a band collar. Vintage-inspired minimalist design.',1699,3299,13,'Harsh Formals',4.6,16,ARRAY['Band Collar','New'],false,false,false,true,'https://images.pexels.com/photos/2974396/pexels-photo-2974396.jpeg?auto=compress&cs=tinysrgb&w=800',ARRAY['White','Off-White'],ARRAY['S','M','L','XL'],48,true),
    ('Premium Oxford Shirt','premium-oxford-shirt','Premium oxford shirt in sky blue. Tailored fit with a button-down collar.',1899,3699,10,'Harsh Luxe',4.8,15,ARRAY['Oxford','Premium'],true,false,true,false,'https://images.pexels.com/photos/8214843/pexels-photo-8214843.jpeg?auto=compress&cs=tinysrgb&w=800',ARRAY['Sky Blue','White','Pink'],ARRAY['S','M','L','XL'],49,true),
    ('Light Blue Casual Shirt','light-blue-casual-shirt','Light blue casual shirt with a relaxed fit. Easy everyday styling.',1399,2699,20,'Harsh Co.',4.4,28,ARRAY['Casual'],false,false,false,false,'https://images.pexels.com/photos/8214843/pexels-photo-8214843.jpeg?auto=compress&cs=tinysrgb&w=800',ARRAY['Light Blue','Sky'],ARRAY['S','M','L','XL'],48,true),
    ('Black Mandarin Shirt','black-mandarin-shirt','Black shirt with a mandarin collar. Sleek, minimalist, and modern.',1699,3299,14,'Harsh Luxe',4.6,18,ARRAY['Mandarin','Premium'],true,false,false,true,'https://images.pexels.com/photos/769749/pexels-photo-769749.jpeg?auto=compress&cs=tinysrgb&w=800',ARRAY['Black','Charcoal'],ARRAY['S','M','L','XL'],48,true),
    ('Blue Band Collar Shirt','blue-band-collar-shirt','Blue band collar shirt for a clean, contemporary look. No collar, no fuss.',1599,3099,15,'Harsh Formals',4.5,17,ARRAY['Band Collar'],false,false,false,false,'https://images.pexels.com/photos/8214843/pexels-photo-8214843.jpeg?auto=compress&cs=tinysrgb&w=800',ARRAY['Blue','Navy'],ARRAY['S','M','L','XL'],48,true),
    ('Black Slim Casual Shirt','black-slim-casual-shirt','Black slim fit casual shirt. A versatile essential for any occasion.',1499,2899,22,'Harsh Co.',4.5,32,ARRAY['Slim','Casual'],false,true,true,false,'https://images.pexels.com/photos/1183266/pexels-photo-1183266.jpeg?auto=compress&cs=tinysrgb&w=800',ARRAY['Black','Charcoal','Grey'],ARRAY['S','M','L','XL'],48,true)
  ) AS p(name, slug, descr, price, mrp, stock, brand, rating, rc, badges, feat, trend, best, newb, img, colors, sizes, disc, cod)
  ON CONFLICT (slug) DO NOTHING;
END $$;
